# This workflow will run a build on when opening or pushing to a PR. It performs
# a clean installation of node dependencies, cache/restore them,
# and build the source code and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull request

# Activate only on pull requests
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test